### ISSUE TITLE
Licence of usage

### ISSUE THREAD

**Issue by theodorosploumis** [gaarf/XML-string-to-PHP-array#9]
Hi @gaarf,

I am using this php class with a [Drupal 7](https://www.drupal.org) module. Can you please add a **licence** so I know if I know if I should include this library as an external library or add it directly?

Drupal can use directly libraries if are licensed under [GPL](http://www.gnu.org/licenses/old-licenses/gpl-2.0.html).

Thanks a lot for this library!

**Comment by gaarf** [comment]
@theodorosploumis hope this works for your needs! Feel free to use this function however you like, just don't sue me :cop:
